import '@material/web/button/filled-button.js'
import '@material/web/button/outlined-button.js'
import '@material/web/fab/fab.js'
import '@material/web/icon/icon.js'
import '@material/web/iconbutton/icon-button.js'
import '@material/web/checkbox/checkbox.js'
import '@material/web/slider/slider.js'
